name: Build and Deploy Demo on Release / Push to Main / Manual Run

on:
    release:
        types: [published]
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            ref:
                description: 'Git ref (branch or tag) to build (defaults to main)'
                required: false
                default: 'main'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        # Allow release from main, push to main, OR manual runs.
        if: >
            (github.event_name == 'release' && github.event.release.target_commitish == 'main')
            || (github.event_name == 'push' && github.ref == 'refs/heads/main')
            || (github.event_name == 'workflow_dispatch')
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || '' }}
                  fetch-depth: 0

            - name: Install Yarn
              run: npm install --global yarn

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install dependencies and build
              run: yarn && URL_BASE_PATH=/jelly-app/ yarn build && cp dist/index.html dist/404.html

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: needs.build.result == 'success'
        environment:
            name: github-pages
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
